name: Create release

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build src/Localizati18n.ResourceGenerator/Localizati18n.ResourceGenerator.csproj --configuration Release --no-restore 
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack Manager
      run: dotnet pack -c Release src/Localizati18n.ResourceManager/Localizati18n.ResourceManager.csproj
    - name: Pack Generator
      run: dotnet pack -c Release src/Localizati18n.ResourceGenerator/Localizati18n.ResourceGenerator.csproj
    - name: Publish Manager
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}
      run: dotnet nuget push src/Localizati18n.ResourceManager/bin/Release/*.nupkg --skip-duplicate -n true -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
    - name: Publish Generator
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}
      run: dotnet nuget push src/Localizati18n.ResourceGenerator/bin/Release/*.nupkg --skip-duplicate -n true -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
